# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YoutubeFavApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
  # Pods for YoutubeFavApp

  target 'YoutubeFavAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YoutubeFavAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
