# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MasterDocumentHandlerExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'SVProgressHUD'
pod 'SwiftyDropbox'
pod 'Google/SignIn'
pod 'GoogleAPIClientForREST/Drive'
pod 'GTMOAuth2'
pod 'Alamofire'
pod 'SwiftyJSON'
  # Pods for MasterDocumentHandlerExample

end
