# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoQB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'AFNetworking', '~> 3.0'
pod 'TPKeyboardAvoiding'

# Pods for MBProgressHUD
pod 'MBProgressHUD', '~> 1.0.0'

# Pods for StarRatingView
# pod 'Cosmos', '~> 6.0'

# Pods for Facebook
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'

# pod 'PatrickValidator'

# Pod For load images
pod 'SDWebImage/WebP'

# Pods for JSON
# pod 'SwiftyJSON'

pod 'MMDrawerController'

# Pods for Quickblox
pod 'QuickBlox'
pod 'QMChatViewController'
pod 'QMServices'
pod 'SVProgressHUD'
  # Pods for DemoQB

end
